### ISSUE TITLE
Falta un generador de mapas

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/mano-gift#1]
```
Hacer cada mapa a mano suena tedioso, aburrido, y sumamente laborioso. Seria 
prudente diseñar primero un generador de mapas que nos ayudara a crear el 
código directamente.

```

Original issue reported on code.google.com by `daniel.e.rossy` on 4 Nov 2012 at 12:05

**Comment by zenieldanaku** [comment]
Cierro este issue porque 1) el generador de mapas ya es un proyecto independiente y, 2) la dirección a la que remite este issue está desactualizada.
