### ISSUE TITLE
Sombra en el cenit.

### ISSUE THREAD

**Issue by danielrossyamitrano** [ludica-squamata/mano-gift#100]
Si el sol está en el cenit, el objeto no debería "proyectar" una sombra, sino tener una sombrita debajo (como hacen muchos juegos), porque la sombra estaria proyectada _por debajo_ del objeto.

Blocked on: #64 Posicionamiento de las sombras

**Comment by zenieldanaku** [comment]
Este es el centécimo issue ^^
