### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by einacio** [ludica-squamata/mano-gift#107]
Para poder promocionar el engine se necesita un demo.

Hagamos uno que muestre lo mas posible de las funciones que tiene ahora. Seguramente tambien encontremos cosas que no funcionan del todo bien y haya que corregir

**Comment by zenieldanaku** [comment]
"Hagamos"...

**Comment by zenieldanaku** [comment]
Este issue se está trabajando del en branch demo y en la PR #127

**Comment by einacio** [comment]
un issue no se cierra hasta que un PR lo resuelve y se mergea.

**Comment by zenieldanaku** [comment]
Lo había cerrado porque el PR en sí es un issue (con numero propio y todo) y en la milestone aparecen los dos como si fueran cosas separadas.

**Comment by zenieldanaku** [comment]
Lo cierro porque no se me ocurre nada para hacer un demo y hasta que no haya al menos una idea no quiero tener este issue colgandome de la cabeza.
