### ISSUE TITLE
Mejorar las event flags.

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#114]
Estuve pensando en que las flags que hay (botonstep y door activate) si bien funcionales, están mal escritas. Para empezar, boton step no hace nada por si mismo, solo ejecuta una funcion de ModState (set) y lanza un evento, dos veces.
Dicho evento (door activate) no hace uso del evento per se (de hecho, hay que hacer del event para que PyCharm no tire error de variable inútil) y encima se escucha dos veces.
Pensé entonces, que podría haber, junto a ModState, una clase EventFlag, de la cual las flags de usuario heredarian, que implementara por default la interacción con ModState.
Además, por como estan las flags ahora, debuggearlas es un bardo, porque la definición esta repartida por todos lados.

**Comment by einacio** [comment]
mmm, dejame recordar como era esto...

habia dos botones en el piso. cada boton tenia un evento (creo que
compartian el mismo pero interpretaba el id del boton). cada uno de los
eventos marcaba el flag de que habia sido pisado y avisaba.
a su vez habia una puerta. la puerta escuchaba a cada vez que se pisaba un
boton, y revisa los flags. si ambos flags estan seteados (o sea, se pisaron
ambos botones), la puerta se abre.

en resumen,
- boton_step si hace algo, setear un flag y desencadenar un evento
posterior.
- la funcion ModState.set es lo que marca un event flag   (entiendase que
lo importante es "flag", una señal/indicador/estado. "event" es solo un
coloquialismo porque esta pensado para usarse dentro de eventos, pero
podria usarse en cualquier lado). no existe tal cosa como "flags de
usuario", porque siempre son de usuario (el sistema puede usar sus
variables globales para setear estado si quiere, aunque podria usar este
sistema)
- door activate se dispara dos veces por diseño. de hecho, todas las que
veces que se pise un boton, y la puerta se abre y cierra segun corresponda
a la cantidad de botones que esten presionados.


. que definicion esta repartida por todos lados? la clase ModState es una
sola. el script del modulo esta todo junto





2017-04-09 21:37 GMT-03:00 Daniel <notifications@github.com>:
