### ISSUE TITLE
Agregar un score meter

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#117]
Se me ocurrió recién cuando me levanté una suerte de Skinner box sencilla, que es uno de los features que tenemos escritos en "un proyecto sencillo". La idea es simple: crear un event_listener que, al activarse, sume puntos a un contador que aparecería en la pantalla. Los puntos vendrían de eventos como "mob muerto" u "objeto adquirido", cosas así.

**Comment by einacio** [comment]
no creo que sume mucho tener un evento para sumar los puntos, podria
hacerse sincrono sin mayor dificultad, al fin y al cabo es solo leer un
valor durante el update del sprite del score

2017-05-06 8:32 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
Este issue, como otros de la misma naturaleza, es un issue de un juego, no del enigine. Por lo tanto, es inválido.
