### ISSUE TITLE
hacer que mob sea event aware y que la Al lance eventos 

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#118]
El título lo dice todo. Porqué mob (y por extensión, NPC), no puede responder a eventos? Porque los eventos son de teclado, era la respuesta. Pero, por qué no hacer que mob, directamente, escuche eventos?
Serían, en el caso del PC, eventos del teclado, pero para el caso de los NPC, la Al podría evitar eventos propios, correctamente taggeados. Lo que es redundante no es PC, como habíamos dicho. Lo que es redundante es Autónomo, que además es mentira: los NPCs no son autónomos, son con controlados por la AI.
@einacio, que te parece?

**Comment by einacio** [comment]
yo digo que mob no deberia ser event aware, sino las ai.
y que pc es redundante, basta con tener una ai que acepte eventos de
teclado para controlar el mob del jugador

2017-05-10 21:25 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
@einacio 
El tema es que las "AI" son los árboles de comportamiento y, la función que acciona las hojas no lleva argumentos (aunque deberían) como para aceptar eventos y convertirlas en event handlers

**Comment by zenieldanaku** [comment]
Creo que se me acaba de ocurrir una implementación para eso que llamaste "AIs que acepten eventos"

**Comment by einacio** [comment]
Como es tu idea?

la mia era que cuando se crea un mob tenga en el json la posibilidad de
registrar un event handler

**Comment by zenieldanaku** [comment]
Lo que habia pensado era agregar un listener a las leaves que ejecutara la función real cuando recibiera el evento. Lo mismo que hace EventAware básicamente.

**Comment by zenieldanaku** [comment]
Lo que me parece que no terminas de entender es que la IA no se termina en el json.

**Comment by einacio** [comment]
el json decia como punto de entrada nomas, se que no estan definidas ahi.

**Comment by zenieldanaku** [comment]
Los árboles son una parte data (json) y otra parte código. Los nodos que hacen cosas (las leaves) las define el modder y van en data. Los nodos relativos a la estructura del arbol (composites y decoratores) son del engine. El json define la "silueta" del árbol, su estructura a grosso modo, la secuencia de cuál nodo conecta con cuál.
En la definición del mob, el modder podría indicar nombre de un árbol  (commoner hace eso mismo), pero el tema es que las acciones del héroe se ejecutan en un tick. Son instantáneas. Las acciones ejecutadas por un árbol de comportamiento toman, como mínimo, tantos ticks como nodos intermedios haya entre la raíz del árbol y la hoja en cuestión.

**Comment by zenieldanaku** [comment]
Algo que podría implementar sería una nueva clase de Selector, que funcione enteramente a base de inputs del teclado

**Comment by zenieldanaku** [comment]
O, mejot

**Comment by zenieldanaku** [comment]
O también una nueva clase de decorator...

**Comment by zenieldanaku** [comment]
Borré toda la discución que había porque no llegaba a ningun lado, y quería destacar este comentario. Hice un resumen de lo que hablamos hoy:

la modificacion consistiría en:
* Agregar una nueva clase CompoMob.ControlableIA o algo así.
* Dicha clase expone un método update() sin argumentos, igual que un BehaviourTree.
* Autónomo no estaría creando un BehaviourTree en su init(), sino una AI().
* Dicha AI() define si se trata de un BehaviourTree o de una ControlableIA según se especifique en la definición json del mob. Es una clase intermedia (o quizás en cambio sólo una función, como sucede con new_prop()).
* ControlableIA.update() sería básicamente lo mismo que hoy existe en PC.accion(). Otras acciones las podría definir el modder, pero escribiendo su propia IA y especificando en el json.
* ControlableIA recibiría los key como eventos y los iría guardando en una variable, y en el update ejecutaría las acciones correspondientes.
