### ISSUE TITLE
pygame.Rect.rect.center Rounds up!

### ISSUE THREAD

**Issue by danielrossyamitrano** [ludica-squamata/mano-gift#119]
Estaba leyendo sobre Rects en la documentación de pygame y me encontré con esto: 

> Rect.center  rounds UP:
> r0x0 = pygame.Rect(0,0,0,0)  # a 0x0 rect
> print('center of 0x0 rect is ' + repr(r0x0.center))  # result is (0,0) = not in the rect!
> r1x1 = pygame.Rect(0,0,1,1)  # a 1x1 rect
> print('center of 1x1 rect is ' + repr(r1x1.center))  # result is (0,0) = correct
> r2x2 = pygame.Rect(0,0,2,2)  # a 2x2 rect
> print('center of 2x2 rect is ' + repr(r2x2.center))  # result is (1,1) = rounded up!
> r3x3 = pygame.Rect(0,0,3,3)  # a 3x3 rect
> print('center of 3x3 rect is ' + repr(r3x3.center))  # result is (1,1) = exact
> r4x4 = pygame.Rect(0,0,4,4)  # a 4x4 rect
> print('center of 4x4 rect is ' + repr(r4x4.center))  # result is (2,2) = rounded up!
> r5x5 = pygame.Rect(0,0,5,5)  # a 5x5 rect
> print('center of 5x5 rect is ' + repr(r5x5.center))  # result is (2,2) = exact
> r6x6 = pygame.Rect(0,0,6,6)  # a 6x6 rect
> print('center of 6x6 rect is ' + repr(r6x6.center))  # result is (3,3) = rounded up!
> r7x7 = pygame.Rect(0,0,7,7)  # a 7x7 rect
> print('center of 7x7 rect is ' + repr(r7x7.center))  # result is (3,3) = exact

A lo cual pensé: si nuestros rects son de 32x32, eso quiere decir que el center (16,16) es incorrecto, porque implica que quedan 16 pixeles a la izquierda del centro y 15 a la derecha. Lo mismo pasa con el rect de la cámara (640x480). Se me ocurre, por lo tanto, incrementar el tamaño de los sprites y el de la camara a valores impares (33x33; 641x481), de forma de tener un pixel central que siempre sea válido.

**Comment by einacio** [comment]
se esta usando el center para algo?
recuerdo que habiamos hablado en un momento de hacer que la pantalla
tuviera una cantidad impar de rects justamente para que el sprite foco
quedara en el cuadro del centro

2017-08-04 13:22 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
El centro del rect del focus de la camara (el heroe) se compara con el centro de la pantalla para verificar que el héroe esté en el centro todo el tiempo. Por el momento funciona bien con un centro inexacto, pero me parece que corregir ese pequeño desperfecto dejaría las cosas más prolijas y menos propensas a errores de +1 o -1 pixel de diferencia.

**Comment by zenieldanaku** [comment]
Además de que HAY que rehacer los sprites a algo un poco más prolijo. Los que están ahora son placeholders como mucho.
