### ISSUE TITLE
Los props pertenecen a Stage o a los Chunks?

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#130]
Hice un experimento en el mapa infinito. Puse un arbol en -2000 de x, a ver qué pasaba, y apareció, inesperadamente, en otro chunk, cargado dinámicamente. Como contrapartida, los props no se repiten, aunque se use el mismo chunck.json dos o más veces (o infinitas veces, como pasa en el mundo continuo), pero esto deja en duda que los props son propiedades del chunk. Más parecen propiedades del stage (que, heck, se añaden a Stage.properties, asi que de algun modo lo son), por lo que me parece que tendría que haber otra capa más de definición de mapas, o poner los mobs y los props devuelta en stage.

**Comment by zenieldanaku** [comment]
Si props y mobs estuvieran declarados en Stage, entonces los stage.json tendrian que decir en qué chunk se encuentra qué mob/prop, lo que haría que stage tuviera una lista de chunks... cosa que choca con la reutilizacion de chunks en el Mundo Continuo.

**Comment by einacio** [comment]
Vayamos desde la base:
cuales son las definiciones de chunk y stage?

**Comment by zenieldanaku** [comment]
Un stage es un conjunto de chunks. Los chunks son las partes individuales de un stage. Un chunk tiene un fondo y otros chunks con los que limita, pero un stage está aislado de otros. Solo se puede pasar de un stage a otro mediante una salida.
En principio, antes de la existencia de los chunks, los props y los mobs estaban en Stage.  Ahora están en los chunks, pero solo se cargan los que están en el primero chunk (al que se accede cuando se entra en el stage que lo contiene).
Una cosa que dije cuando separamos Stage de Chunk es que, en realidad, los objetos y las personas no son parte del mapa en el que viven. Están ahi más por su "historia" personal, que por que el mundo se haya diseñado así. Pero esta es una cuestión más metafísica que práctica.

**Comment by zenieldanaku** [comment]
Otra cosa que se me ocurre es que los mobs listen en su definición en qué chunks pueden aparecer. Algo así como pasa con los monstruos de D&D que ponen, en su ficha de características el terreno donde aparecen ("Llanuras cálidas") y de a cuántos ("banda (3-5)").

**Comment by zenieldanaku** [comment]
Ya está solucionado todo lo que dije en el primer post, desde la [revisión del 27 de Septiembre](d108f8143f3bcdac550a74ea193135f54ed3412b)  de este año por lo menos.
