### ISSUE TITLE
Los botones de Pausa deberían auto-generarse

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#137]
Estaba mirando la historia de los commits y me encontré con [uno](https://github.com/ludica-squamata/mano-gift/commit/13715388b25b39438cf9401a6e21af0ff9ffbcf4) que habla sobre los menús custom. Si bien dicho feature ya está implementado, para visualizar el menú custom de ejemplo hubo que añadirlo, manualmente, a Pausa.

Se me ocurre, entonces, que:
- [ ] Los menúes tendrían que tener alguna marca que indique a que raíz pertenecen (sea Pausa o Principal)
- [ ] Esos menús "raíz" tendrían que generar automáticamente la lista de botones de acceso a los submenus.
- [ ] Tendría que hacerse algo parecido en Menú Opciones, tomando la lista de botones en base a las teclas de config.json

**Comment by zenieldanaku** [comment]
@einacio

**Comment by einacio** [comment]
Me parece buena idea, aunque no prioritaria a menos que veamos que los mods
requieren menus propios frecuentemente

**Comment by zenieldanaku** [comment]
Te mencioné porque recordé que algo así habías propuesto vos una vez cuando implementamos lo de enumerate().

**Comment by einacio** [comment]
Si, tambien me suena como algo que propuse :)

**Comment by zenieldanaku** [comment]
Se me ocurre que podríamos dejarle esta decisión al modder, dejando un espacio en mod.json aclarando qué botones tiene qué menúes. Lo que sería un paso hacia atrás, porque algo así ya había en el pasado (si mal no recuerdo era menues.json), pero es la opción más plausible que se me ocurre.
