### ISSUE TITLE
Números de daño

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#141]
El ya bien cerrado issue #58 mencionaba, entre otras cosas, que en un ataque satisfactorio, aparecieran brevemente una pequeña barra de vida y un número flotante, que sería el daño provocado. [El tema de las pequeñas barras de vida ya fue resuleto](https://github.com/ludica-squamata/mano-gift/commit/45676e843d6ff5dbb7b5b83b75c26a46bcbc2a77), pero quedaría agregar los numeritos flotantes para cerrar completamente aquel issue (aunque no tengo intención de reabrirlo). Dada la fecha de aquel issue (3/6/2014, hace más de 5 años) asigno este issue al milestone 1.0, porque es una característica que "estaba" en el desing document que jamás llegamos a implementar.

Queda entonces (porque me encantan estas listas de tareas): 

- [x] Añadir numeros flotantes, que aparezcan cuando se produce o se cura daño.
- [ ] Los numeros flotantes deberían tener una pequeña animación.
- [x] los numeros flotantes deberían tener colores indicando si son daño (rojo) o curación (verde).
- [x] la aparición de los números, así como el de las minibars, debería ser algo configurable.

En el issue #58 también se mencionaba que, al cambiar el mob sobre el que se tiene control (territorio del issue #122), el nombre que aparece "en una esquina" debería actualizarse, aunque eso no es territorio de este issue tampoco porque aún ni siquiera está el feature que monitorear el el HUD.

**Comment by einacio** [comment]
Agregale a la lista una opcion en configuracion para habilitar/deshabilitar
los flotantes. a algunas personas les molesta, y no cuesta nada un if
