### ISSUE TITLE
Las sombras deben aclararse cuando cae la noche

### ISSUE THREAD

**Issue by danielrossyamitrano** [ludica-squamata/mano-gift#148]
Se me ocurrió que a la noche no hay sombras (al menos, no sombras naturales) porque no está el sol para proyectarlas. Por lo tanto, mediante un evento vinculé el alpha (inverso) de la noche con el alpha de las sombras, y si bien logré que se trasparentaran junto a la noche que se volvía cada vez más opaca, hay un problema en la performance si la cámara se está moviendo.

**Comment by zenieldanaku** [comment]
Podría, se me ocurre, aliviarse un poco la carga de la performance si la tarde/noche no cambiara su alpha tan de golpe. Como está ahora, cada cambio de alpha se da en un tick, cuando en realidad el paso del dia a la noche es algo gradual que se da durante varias horas.
