### ISSUE TITLE
Los Mobs debieran poder causarse daño

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/mano-gift#27]
```
Tanto los enemies a los NPCs y al héroe, como los NPCs a los enemies, los mobs 
deberian poder restarse puntos de vida mutuamente y hasta matarse.
```

Original issue reported on code.google.com by `daniel.e.rossy` on 18 Sep 2013 at 2:57
* Blocking: #7

**Comment by zenieldanaku** [comment]
Estaba viendo el tema de lanzar un evento a la muerte del héroe, pero me quedé pensando: ¿quién es el listener de ese evento? Para mí sería o bien el mod (que dice qué hay que hacer, si tirar una pantalla de game over o qué) o el engine.

**Comment by einacio** [comment]
Yo diría que el mod, para poner la pantalla de game over o hacer un respawn
o lo que se requiera.

Que tiene que ver con los mobs?

**Comment by zenieldanaku** [comment]
No entiendo la pregunta. Varios comentarios atrás se habla de la muerte del héroe, el heroe es un mob, pero nadie (ninguna clase) le está prestando atención a la muerte de los mobs.

**Comment by zenieldanaku** [comment]
Hmmm, estaba viendo que en Mod_data reemplazamos el hook intro() por la funcion intro que provea el mod. Podriamos, se me ocurre, generalizar eso, y decir que por cada script en la carpeta del mod, Mod_data tenga un método con ese nombre. Podemos setearlo usando setattr.

**Comment by einacio** [comment]
Ah, es que recordaba que habíamos hablado de eso en algún otro lado.
Igual lo importante es que el mod puede que capturar eso si quiere,
declarándolo en mod.json. el pc sólo tira el evento al aire

**Comment by zenieldanaku** [comment]
3/3/2016: Lo que quedaba de este issue (el evento de la muerte del heroe) ya está solucionado.
