### ISSUE TITLE
Cambios al "sistema" de diálogos

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/mano-gift#28]
```
El héroe deberia tener otra forma de respondere a los NPCs (por ahora, las 
respuestas del heroe estan escritas en el dialogo del NPC), basada en sus 
caracteristicas como inteligencia o carisma y lo que sepa del mundo, según lo 
que habíamos habladoo.
```

Original issue reported on code.google.com by `daniel.e.rossy` on 18 Sep 2013 at 2:58
- Blocking: #7

**Comment by zenieldanaku** [comment]
Otra cosa que se me ocurre es una suerte de auto-paginación. Sería así: primero se intentaría renderear toda la pagina en la ventana de dialogo. Si es demasiado texto, render_textrect devuelve un error. Usamos ese error en un bucle para reducir la cantidad de palabras de esa pagina, y guardamos el sobrante. Ese sobrante, luego, se pone al inicio de la siguiente pagina y a continuación el texto propio de esa pagina. Podría, también, asignársele algún tipo de bandera a una página para indicar que debe estar precedida por un salto sí o sí.

**Comment by einacio** [comment]
un bucle de try-catch en cada dialogo? muy lento al pedo. mejor calculemos cuantas letras entran maximo en el cuadro o por linea (rendereando una secuencia de 'm', por ejemplo, que es la letra mas ancha), y cortemos automaticamente el texto en palabras de maximo ese largo

**Comment by zenieldanaku** [comment]
Esta bien, pero eso sería deconstruir la función que estamos usando (render_textrect).

**Comment by zenieldanaku** [comment]
A partir de la ultima revisión (esto es una de las cosas que me molestan de git.. las revisiones no tinene numeros claros) una puntuación baja de carisma (o cualquier otro atributo, en realidad), puede ocultar opciones de diálogo.

**Comment by zenieldanaku** [comment]
Sobre el tema de "mostrar un objeto" se me ocurría recién que la opción de mostrar un objeto podría tratarse de la misma forma que las características: si se tiene el objeto en cuestión, aparece la opción de mostrarlo. Y así podríamos ir desbloqueando opciones de diálogo con diferentes cosas, como quests realizadas, o puntuaciones de fama, etc.
Otra cosa que se me ocurrió fue que, de tener el héroe cierto objeto en el inventario, el monólogo del npc podría cambiar (algo así como "hola, heroe", si no tenes el objeto, a "hey, sos de la guardia real!" si llevas la insignia). Esto me parece que habría que implementarlo con cuidado, diferenciando los items que el héroe lleva a la vista (como sus armas y armaduras) de los que no (todo lo que lleva en la mochila) para evitar la tipica situación de los RPGs en los que los NPCs saben que cosas tenes vos encima, aunque las tengas en el fondo de la mochila.

**Comment by einacio** [comment]
podriamos marcar algunos objetos como visible, me parece bien

respecto de numeros de revision, en git se usan los primeros 6 caracteres
del sha-1 para identificar un commit. la idea es hacer muchos commits
atomicos para avanzar, y si queres marcar alguna "version" o milestone
particular hay una opcion llamada tags para eso. igual con decir como venis
diciendo alcanza

el tema de porque no se usan numeros secuenciales es que git esta pensado
para desarrollo distribuido con pushes ocasionales a un repo compartido,
asi que no se puede mantener la correlatividad como en svn que hay una
autoridad central



2015-06-07 19:46 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
Haciendo el cambio para scrollear el texto que subí ayer (4/10/15), me di cuenta hoy de que scrollear un bloque de texto y cortarlo en páginas son recursos distintos que pueden coexistir tranquilamente. Hasta ahora, render_tagged_text(), como lo hacía render_textrect(), devuelve un error si el texto es demasiado largo como para entrar en el rect, pero voy a ver si la cambio para que ignore la restricción de altura, y devuelva un surface tan alto como sea necesario para todo el texto, total después se scrollea.

**Comment by zenieldanaku** [comment]
No sé como vincular este comentario al último commit que hice hoy, pero desde ahora, los diálogos pueden lanzar eventos, y el evento de ejemplo que puse aumenta el carisma del héroe, por lo que también es una demostracion de que los diálogos pueden modificar las características del personaje.

**Comment by einacio** [comment]
para hacer referencia a un commit simplemente pones el id y se hace un link.
el que haces referencia es e3e37a6a422975fe1efda15898c9eaf39a086f6f

**Comment by zenieldanaku** [comment]
Sobre el tema de mostrar un objeto, se me ocurría recién que la forma de mostrar el objeto puede ser _pasiva_ o _activa_.

**Pasiva** sería como lo tenemos hasta ahora. Si el PC tiene un objeto relevante para el diálogo, la opción de de comentar sobre él aparece entre las que se le dan al player para elegir.

**Activa** sería, se me ocurre, cuando el PC gana la iniciativa, aparece un _menu circular_ mostrando los objetos (y temas, si a cada tema le asignamos un ícono) para que el player elija uno. Te parece?

**Comment by einacio** [comment]
me parece bien. haces en un branch una demo para probarlo e iterar el
diseño?

2016-04-09 12:28 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
Quiero dejarlo claro acá, porque sé que lo comenté en otro lado pero no me acuerdo dónde: la idea es que si el player toca hablar para interactuar con un NPC, salta el menú circular. Si es el NPC el que se aproxima al héroe para hablarle (un tema de AI) entonces el diálogo lo "elige" el NPC (es decir, se abre el diálogo por default, o el que esté scripteado, pero no hay menú ni prompt para el player).

**Comment by einacio** [comment]
el prompt del player puede aparecer igualmente cuando el player responde
(si no es una conversacion scripteada)

*NPC se acerca* Heroe, volviste! pudiste rescatar a mi mujer?
*PC* (Si | No, vine a buscar mas pociones | No, cambie de idea y no tengo
ganas | Mostrar objeto -> [Cabeza de ogro | Cabeza de mujer])

2016-04-09 23:37 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
Eso que mencionás es el flow normal de los árboles de diálogo. El bloque de diálogo que corresponde al NPC ("Heroe, volviste! pudiste rescatar a mi mujer?") continua con esas tres opciones. En el caso de las cabezas, esa opciones solo aparecerían si el heroe lleva el ítem en cuestión (Agarrables), igual que pasa ahora con la estrella.

**Comment by zenieldanaku** [comment]
Cierro este issue porque abri otro con la información sobre lo que hay que hacer mas actualizada.
