### ISSUE TITLE
Falta interacción entre los mobs y los props

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/mano-gift#29]
```
Además del héroe, los NPCs deberian poder abrir puertas y empujar cosas. Los 
enemies, ademas de empujar, deberian poder romper ciertos props (como la caja, 
por ejemplo).
```

Original issue reported on code.google.com by `daniel.e.rossy` on 18 Sep 2013 at 3:00
- Blocking: #7

**Comment by zenieldanaku** [comment]
Todos los mobs pueden, en teoría, operar sobre puertas y similares. Lo que queda es un tema de AI, que no  se resuelve en este issue.
