### ISSUE TITLE
Definir sistema de inventario para los mobs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/mano-gift#31]
```
Tenemos que decidir qué slots van a haber en el cuerpo del héroe y de los 
mobs en general, para decidir por ejemplo cuantas van a ser las piezas de 
armadura. Tambien tenemos que categorizar los items agarrables, y fijanos como 
hacer el sistema de evalualcion de volummenes, peso y carga maxima de la 
mochila.
```

Original issue reported on code.google.com by `daniel.e.rossy` on 30 Sep 2013 at 3:09

**Comment by zenieldanaku** [comment]
Otra cosa que está relacionada con este issue es el tema de mostrar los items equipados, el arma y la armadura como mínimo.

**Comment by einacio** [comment]
si, pero eso requiere tener que hacer un montooon de imagenes adicionales, que no se quien querria hacer. supongo que podria hacerse opcional y con un generico como placeholder para los equipos que no declaran imagen

**Comment by zenieldanaku** [comment]
en algun punto las imagenes las tengo que hacer igual si los items van a aparecer tirados en el suelo para ser agarrados. la opción sería que aparezca en el suelo del mapa un ícono genérico de "item" (cosa que no me convence).

**Comment by zenieldanaku** [comment]
Hmmm, estaba viendo que en Mod_data reemplazamos el hook intro() por la funcion intro que provea el mod. Podriamos, se me ocurre, generalizar eso, y decir que por cada script en la carpeta del mod, Mod_data tenga un método con ese nombre. Podemos setearlo usando setattr.

**Comment by zenieldanaku** [comment]
Las dos cosas pendientes de este issue ya están cubiertas por otros issues individuales: #104 Mostrar ítemes equipados y #42 Definir el sistema de estadísticas de los mobs.
