### ISSUE TITLE
Mejorar los sentidos de los Mobs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/mano-gift#35]
```
Por el momento, los Mobs pueden ver solo en un cono de unos 90º al frente. Se 
me ocurre que se podría añadir una 'audición' que hiciera que los mobs 
pudieran escuchar a quien hace ruido (y habria que determinar cuándo se hace 
ruido, quizás caminando sobre hojas secas, o hablando) y acercárcele. 

También, otros tipos de conos de visión. Se me ocurre que criaturas mas 
grandes tendrían conos más largos (con el mismo ángulo o más estrecho), o 
que, en lugar de un cono frontal, la visión fuese como la de los caballos, que 
pueden ver casi en 360º.
```

Original issue reported on code.google.com by `daniel.e.rossy` on 5 Oct 2013 at 9:12

**Comment by zenieldanaku** [comment]
Ahora los mobs pueden detectar mediante visión también a los objetos interactuables del mapa.

**Comment by zenieldanaku** [comment]
Los mobs ahora también pueden "oir" al héroe si éste se está moviendo en su área de audición.

**Comment by zenieldanaku** [comment]
El primer post, se dice que:

> criaturas mas grandes tendrían conos más largos (con el mismo ángulo o más estrecho)

Por otro lado, en Sensitivo:

`self.vision = Sight(self, 32 * 5)  # (data[vision])`

Ese comentario está como referencia de cómo quedaría ese número si viniera de los datos del mob.json.
Lo que pregunto es cómo se vincularía ese valor (32*5) al tamaño del mob? Como está puesto ahí, es un valor arbitrario, pero tendría que guardar algun tipo de relación? cuál sería?

**Comment by einacio** [comment]
yo diria que los datos pueden ser un valor numerico o un valor de texto que
se traduzca internamente ( 'estandar', 'lejano')

2018-02-01 11:41 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
Eso no responde lo que pregunté. La pregunta es: que relación hay entre el tamaño del mob y su sentido de la vista?
