### ISSUE TITLE
Incluir concepto de latitud

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/mano-gift#41]
```
Modifiqué un poco la clase Tiempo para que calcule más precisamente el tiempo 
de juego, y agregué un concepto de hora que antes no estaba. Haciéndolo, me 
di cuenta que el juego arranca en hora 1, y se hace de noche a la hora 12, y 
vuelve a amanecer tras la hora 24. Si bien es correcto que así sea, se me 
ocurrió que, en realidad, acá amanece a las 6 y anochece tipo 9 o 10, y en 
seguida pensé 'acá estamos en clima templado'. A lo cual se me ocurrió que 
podríamos incluir regiones y climas al juego, primariamente para determinar a 
qué hora amanece y a que hora se hace de noche.
```

Original issue reported on code.google.com by `daniel.e.rossy` on 28 Nov 2013 at 10:31

**Comment by zenieldanaku** [comment]
Encontré algo relacionado en [TV Tropes] (http://tvtropes.org/pmwiki/pmwiki.php/Main/EternalEquinox).

**Comment by einacio** [comment]
es un detalle que podemos ajustar despues, ya que son variables las que
determinan el cambio a la noche. con una funcion sencilla podemos ajustarlo
dinamicamente

**Comment by zenieldanaku** [comment]
Se me ocurrió que en engine.ini podemos poner una varible que diga si el engine usa o no el concepto de latitud, y luego en el mod.json que diga con qué latitud se empieza.

Además del ciclo de día y noche, la laitud también modifica las estaciones.

**Comment by einacio** [comment]
ah, pero el mundo del juego tiene latitudes? eso yo diria que mas bien
tiene que ir en mod.ini si se van a usar estos conceptos

2015-10-27 12:31 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
mod.json. Y, aunque es un buen punto, pensé que poner "use_latitude"=true, "initial_latitude"= 0 en el mismo archivo es como redundante. Si hay un numero de latitud, entonces lo usamos, si no, no.

**Comment by einacio** [comment]
mod.json use_latitude:true, map-x.json latitude:x.
mas que nada un valor global para saber si habilitar el checkeo cada minuto
o algo asi

**Comment by zenieldanaku** [comment]
Al respecto de este issue, una cosa que se me ocurría el otro día: cada cuantos chunks el héroe cambiaría de grado de latitud? digo, si cada grado de latitud cambia con 1 chunk, entonces de Norte a Sur el mundo tiene 180 chunks, despues del polo sur al polo norte de vuelta otros 180, y otros 360 chunks partiendo del meridiano 0º hasta volver. Lo cual, si hago bien la cuenta, son 129.600 chunks para cubrir todo el mundo.

**Comment by zenieldanaku** [comment]
O quizás, pensandolo más, a medida que te acercas a los polos cada chunk tendria que valer menos y menos grados (dos chunk por grado, tres chunks por grado, cosas asi).

**Comment by zenieldanaku** [comment]
Me acabo de dar cuenta de que la latitud en la que se encuentre el heroe afecta la hora  en la que amanece, atardece y anochece (porque todo tiene que ver con el horizonte), a lo cual esos valores que pusimos por encima son innecesarios, pues todo puede calcularse desde la posición y altura del observador y la hora del día (AKA rotación y traslación del mundo en relación al sol).

**Comment by zenieldanaku** [comment]
Aunque también me doy cuenta de que eso fue precisamente lo que dijiste en el segundo post :P

**Comment by einacio** [comment]
Todo depende también de la forma del mundo. Marte tiene valores diferentes, y después tenés cosas como mundo anillo y mundodisco
