### ISSUE TITLE
Definir el sistema de estadisticas de los mobs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/mano-gift#42]
```
de momento hay fuerza, velocidad y salud, no se si seria necesario agregar algo 
mas (mana?)
```

Original issue reported on code.google.com by `moguchic...@gmail.com` on 4 Dec 2013 at 5:13

**Comment by zenieldanaku** [comment]
En el issue #31 queda por definir cómo afecta el equipo a las estadísticas de los mobs, pero para eso primero se tiene que resolver qué estadísticas tienen los mobs, lo cual es territorio de éste issue.

**Comment by zenieldanaku** [comment]
Te parece si dejamos este issue a la Pokemon? Sería Ataque (fuerza), Defensa, Ataque especial (Maná), Defensa especial, Velocidad y Salud.

**Comment by einacio** [comment]
Me parece bien como primer enfoque. Algo simple para avanzar

**Comment by zenieldanaku** [comment]
Son las caracteristicas de la G2. No vamos a copiar el error de la G1 con ESPECIAL y hacer que los pokemon psiquicos sean invencibles.. oh, wait, ese es otro juego :P

**Comment by zenieldanaku** [comment]
Creo que también habría que agregar un parámetro más, "Social" digamos, para que trabaje con las opciones de diálogo.

**Comment by einacio** [comment]
Arranquemos con la versión simple y después vemos que se necesita

**Comment by zenieldanaku** [comment]
Los atributos de los mobs son: Acción y Defensa (Física), Acción y Defensa (Especial), Acción y Defensa (social), Velocidad, Salud y Maná.
