### ISSUE TITLE
PNJs tenderos, e interfaz de compra/venta

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/mano-gift#53]
```
Estaba leyendo (otra vez) el articulo de la wikipedia en inglés sobre los RPG, 
y leí lo siguiente: "Players can trade items for currency and better 
equipment. Trade takes place while interacting with certain friendly non-player 
characters, such as shopkeepers, and often uses a specialized *trading screen*" 
([http://en.wikipedia.org/wiki/Role-playing_video_game#Items_and_inventory 
Wikipedia]).
Y me quedé pensando en este _trading screen_. Creo que deberíamos hacer uno y 
la interfaz de compraventa en general. 
```

Original issue reported on code.google.com by `daniel.e.rossy` on 13 Mar 2014 at 3:32

**Comment by zenieldanaku** [comment]
@einacio Te parece que este issue debería resolverse con un nuevo menú o de alguna otra forma? Claramente es algo que queda a decisión del modder, pero igual me gustaria tener algo por default.

**Comment by danielrossyamitrano** [comment]
Para que haya una intefaz de compra y venta, el heroe tendría que tener alguna forma de recolectar dinero. Una forma de hacer esto que aparece en muchos juegos es vender las cosas que vamos encontrando o las armas que ya no utilizamos. Nunca entendí esta mecánica yo, porque en el mundo real en el que vivimos los dueños de tiendas no te compran nada, vos sos el que les compra a ellos.

**Comment by einacio** [comment]
En el mundo actual, los vendedores pueden conseguir las cosas de manera mas consistente y barata usando proveedores, asi que la plata se gana trabajando en un proveedor.

Pero pensa tambien en tiendas de segunda mano de libros o ropa, esos compran directo todavia.

**Comment by danielrossyamitrano** [comment]
> Pero pensa tambien en tiendas de segunda mano de libros o ropa, esos compran directo todavia.

Nunca compré ropa de segunda mano. Y libros míos solo vendí cuando estaba en la escuela primaria: le vendíamos nuestros libros del año anterior a los alumnos que estaban un año antes que nosotros, y con esa plata (más un plus) comprabamos los libros del año, a veces de alumnos de años superiores. Pero de todo eso se encargaba mi vieja.

**Comment by danielrossyamitrano** [comment]
En el mundo real, en el face to face, no hay una "interfaz" de compra/venta. Uno habla comunica al comernciante lo que quiere comprar y el comerciante lo acerca. Uno paga y se lleva su ítem. A ésto se le llama "over the counter".

Otra opción es que uno agarre lo que quiere de las estanterías de un supermercado ("autoservicio") y lo lleve directamente a la caja (a hablar/pagar, etc).

Lo que intento decir es que toda la interacción de compra venta podría ser dada simplemente con diálogos e interacción con objetos del mapa.

**Comment by einacio** [comment]
el engine deberia tener la posibilidad de crear ventanas de interaccion,
las posibilidad de hacer dialogos con opciones y la posibilidad de
interaccionar con objetos, pero despues como se usan es problema del juego.

yo no me gastaria en incluir esos conceptos en el engine. para el caso, se
puede implementar una tienda simplemente con el sistema de dialogos, no es
relevante
podes incluir una implementacion en un ejemplo, pero no compliques el
engine agregando eso.

**Comment by danielrossyamitrano** [comment]
> el engine deberia tener la posibilidad de crear ventanas de interaccion,

Con eso te referís a algo así como un menú, no? Algo así como un pop-up. Hablás con un mob, elegis "comprar" y se te abre un menú. Así decís?

**Comment by einacio** [comment]
claro, solo tenes que dar cosas genericas. tambien podes no hacerlo y que
se manejen con otra cosa

**Comment by danielrossyamitrano** [comment]
Una cosa que se está perfilando en como voy resolviendo este issue es que los ítems del vendedor están declarados en el diálogo que el héroe tiene con ese vendedor, lo cual si bien en principio funciona, no me parece que sea muy escalable por que una vez que se cierra el diálogo, los ítems volverían a aparecer, dado que el json del diálogo no se edita desde el juego.

Por otro lado, en los rpgs generalmente el diálogo con los npcs vendedores es siempre el mismo independiemente del momento del juego y la lista de items. Al tener los ítems declarados en el diálogo, esto hace que sea obligatorio escribir un diálogo distinto para cada comerciante.
