### ISSUE TITLE
Agregar HUD

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/mano-gift#58]
```
Es necesario que agregemos algun tipo de forma de ver la vitalidad del héroe, 
sus puntos de mana, y otras cosas por el estilo.

También se me ocurre que podriamos agregarle una pequeña barra de vida (o un 
contador) sobre la cabeza de cada mob, una vez que recibiera daño.

Otra cosa que creo que vine a lo mismo es que, me parece, estaria bueno poder 
ver cuanto daño le hace el héroe a los mobs (y visceversa) mediante un 
numerito que se eleva en el aire y luego desaparece cuando golepas algo.
```

Original issue reported on code.google.com by `daniel.e.rossy` on 3 Jun 2014 at 8:21

**Comment by zenieldanaku** [comment]
Si vamos a permitir alternar el control entre diferentes personajes de la party, entonces una parte del HUD podría mostrar cuál es el personaje actual, o algo así.

**Comment by einacio** [comment]
Puede ser el nombre en una esquina, pero en principio para el juego la
camara esta centrada, deberia ser posible de identificar

**Comment by zenieldanaku** [comment]
Hay que eliminar los cuadros de inventario (ver #68), y reeemplazar el acceso con otra cosa (quizás el menu circular), porque esos cuadros sugieren que vamos a estar usando los numeros del teclado como hotkeys, lo cual no es cierto.

**Comment by zenieldanaku** [comment]
el hud ya muestra la vitalidad y el mana del héroe, así como su nombre. si otros elementos del hud se vuelven necesarios en el futuro, se abrirán nuevos issues según corresponda.
