### ISSUE TITLE
Actualizar los Docs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/mano-gift#63]
```
El archivo de truck/docs más nuevo data de la r97, y vamos por la 225 al 
momento de escribir este issue. Me parece que habría que actualizarlo 
bastante, pero para hacerlo habria que discriminar qué es importante que el 
usuario del engine sepa (después de todo, docs es la carpta "api" del engine, 
si lo entiendo bien) y cuales son puramente de sistema.

```

Original issue reported on code.google.com by `daniel.e.rossy` on 20 Jul 2014 at 2:20

**Comment by zenieldanaku** [comment]
un nuevo archivo "doc/main.md" es el primer paso para actualizar la documentación, mediante una wiki portable

**Comment by zenieldanaku** [comment]
Cierro este issue porque mantenerlo abierto para recordarnos que hay que actualizar los docs es innecesario ahora que tenemos la wiki.
