### ISSUE TITLE
Alternar el control entre diferentes mobs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/mano-gift#65]
```
Habíamos llegado a la conclusión de que el héroe es tan sólo un mob más 
del montón, por lo que el control que el player tiene sobre él es algo 
"extra" que debería poder sacarse. Esto es, el player tendría que poder 
alternar su capacidad de control directa entre diferentes mobs (con un límite, 
claro, a los mobs específicos que puede controlar... los de la party por 
ejemplo, pero no los monstruos). 
```

Original issue reported on code.google.com by `daniel.e.rossy` on 22 Sep 2014 at 7:55

**Comment by zenieldanaku** [comment]
Se me ocurre que el control podría alternarse de una manera similar a como controlamos los menúes. En lugar de tener una constante "HEROE" en EngineData, tendríamos una variable "heroe_actual" (igual que mapa_actual) que iria cambiando a medida que se fuera alternando el control. En modos pasaría lo mismo. Ed.heroe_actual.accion().

El único tema es que los menúes son clases individuales, que si bien se controlan mediante las mismas teclas, se ven y hacen cosas distintas. No sé si podemos aplcar la misma lógica a los mobs.

**Comment by zenieldanaku** [comment]
Otra cosa que se me ocurre es que las acciones que Modo.aventura lista como consecuencia de un tap hold o release de una tecla, sean eventos en lugar de comandos directos. Esto es, en lugar de ED.HERO.accion(), tendriamos algo como EventDispatcher.trigger('accion', {datos}) o algo así.

Otra cosa que me gustaría seria no tener que llamar a EventDispatcher cada ves que quiero lanzar un evento, pero no se me ocurre cómo.

**Comment by zenieldanaku** [comment]
Lo anterior tiene que ver también con el issue #67 porque el evento se lanzaria en un primer tick, pero la ejecución recién se llevaría a cabo en el siguiente.

**Comment by einacio** [comment]
No hay otra forma de agregar eventos que no sea agregándolos en la lista de
eventos, no es tan grave.

Para este caso particular, como los eventos de io se revisan al principio
del update, el mob los procesaría en el mismo tick. Ahora que lo pienso,
con eventos era una manera que se me había ocurrido de separar a PC del
teclado, pero en ese momento no teniamos un event loop interno

**Comment by zenieldanaku** [comment]
Dos cosas:
+ Azoe Event podría agregarse solo a la cola de EventDispatcher. Se me hace, creo, menos lioso hacer `AzoeEvent("Event","origin",{"key":value})` que `EventDispatcher.trigger("Event","origin",{"key":value})`

  Además de que el import statement sería algo más corto y prolijo.

+ Por otro lado, en ninguna de las instancias en las que vengo usando los eventos estoy tomando en cuenta el `origin`. 

Vale decir también que la clase aún se llama GiftEvent, cuando debiera llamarse Azoe igual que todo el resto del sistema!

**Comment by einacio** [comment]
No lo veo muy complicado declarar la intención con un método, en vez de que
sea un efecto secundario implícito de la creación de una clase.

Lo de origin es porque todavía no le dimos mucho uso, pero en principio
sirve para debugging

**Comment by zenieldanaku** [comment]
Diseminando los componentes de la class PC creo que llegamos al punto de poder alternar el control entre otros mobs. El problema, creo, viene de la mano del __init__. Un pj controlable es EventAware, mientras que un NPC es fundamentalmente Autónomo. Se me ocurre, capaz, hacer una clase híbrida, que pueda saltar de una inteligencia a la otra, pero mantener las clases separadas y aún así altenar el control se me hace muy dificil.

**Comment by zenieldanaku** [comment]
updated
