### ISSUE TITLE
Separar los momentos de proceso de los momentos de muestra

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#67]
Una cosa que te comenté fue una idea que, creo, leí por algun lado, y que me viene dando vueltas en la cabeza desde hace un tiempo: ¿podriamos ganar algo de optimiazación moviendo toda la parte del proceso de datos a los frames impares y mostrando el resultado de esos procesos en los frames pares?

No sé si necesariamente tendriamos que correr a 30. Que pasaría si, en lugar de 60, limitaramos el bucle a 120? diviendolo a la mitad, quedaria igual que ahora?

**Comment by einacio** [comment]
Si no puede correr a 60 haciendo las dos cosas, como correría a 120?

Lo que puede hacerse es correr los procesos en una cola, se ejecutan los
que se puedan en medio frame y el resto en el siguiente.

**Comment by zenieldanaku** [comment]
Y cómo haces para decirle al intérprete que corra los procesos en una cola?

**Comment by einacio** [comment]
hacieno una cola. esta es una idea de como funcionaria, no creo que sea muy
performante realmente, solo es una explicacion

cola_de_procesos = deque() # es una lista a la que van agregandose
funciones anonimas con appendleft
[...]
def agregar_proceso(self, fun):
  self.cola_de_procesos.appendleft(fun)
[...]
def procesar(self):  # procesar se llama entre el update (que agregar
funciones a la cola) y el render
  ticks = Timer.ticks # o algo asi, la funcion que media tiempo de pygame
  limite = ticks + 500  # o como sea para agregarle medio frame
  while ticks < limite:
    self.cola_de_procesos.pop()()  # el primer par de parentesis es tomar
un elemento, el segundo es ejecutar el elemento
    ticks = Timer.ticks

**Comment by zenieldanaku** [comment]
Claro, pero digo, TODOS los métodos pasan por ahí? Incluida la deteccion de colisiones, los nodos de los Behaviour Trees, la detección de mapas adyacentes de Renderer.Camara, etc.? Para llamar ese método que llama a otros métodos habría que poner el módulo que lo contiene por encima de todo, sin que tenga que llamar a nadie para evitar conflictos de import.

**Comment by einacio** [comment]
no estoy seguro de donde lo implementaria, es solo una idea suelta.
de todas maneras creo que si le pasas referencias a funcion no necesitar
las dependencias (no llama metodos, solo los ejecuta). tendria que probarlo.

una opcion es que la lista tenga los update. o sea, cuando se hace el
global que recorre la lista de sprites ejecutando el update, que solo
recorra hasta donde le da el tiempo y despues sigue en el siguiente frame.
se puede hacer con un contador recorriendo un Ordereddict o algo asi

2018-02-01 13:09 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
No me parece que este issue sea solventable por como está armado el proyecto. Si lo hubiésemos pensado desde el principio, quizás podríamos haber usado concurrent execution o threads, pero reescribir **TODO** ahora para que funcione asincrónicamente, no lo veo factible. En todo caso se reabrirá este issue o se hará uno nuevo más específco.
