### ISSUE TITLE
Tutoriales

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#68]
Mencionaste hoy (5/10/15) que eventualmente vamos a tener que hacer un tutorial para enseñar como jugar a nuestro juego (o como usar nuestro engine, más bien). 

Ahora mismo tenemos 4 teclas básicas (accion, hablar, cancelar diálogo e inventario), además de las teclas de movimiento (que, a mi entender, son bastante simples de entender dada la perspectiva); shift, que cambia la posicion del personaje y enter.
- **acción**: sirve para interactuar con objetos (por ejemplo, abrir puertas) y para atacar cuando se está en posicion de combate. También es la que se usa para agarrar objetos que se encuentren en el suelo. 
- **hablar**: funciona como "aceptar" para todo lo que es interacción con menúes, y para iniciar y avanzar el diálogo con los ncps.
- **cancelar diálogo**: como su nombre implica, cierra diálogos y menues. También sirve como "undo" en el menu equipo. Habría que ver aún el efecto in-game de un diálogo cancelado (digo, dejar al npc hablando solo).
- **inventario**: provee acceso a los slots de inventario de la GUI. Dicha GUI va a volar porque no estamos usando los números como hotkeys, que es lo que ese array de cuadros sugiere, a lo cual se me ocurre que esta tecla podria abrir un menu circular (si es que implemento eso en algun momento) con los items que se tienen, o algo así.
- **shfit**: su única función es cambiar la posición de "idle" a "combate" y visceversa. Cambiar a posición de combate permite atacar con la tecla acción, y tocar esa tecla en posicion "idle" acciona objetos operables. Pero nada de esto es mérito de shift.
- **enter**: pausa el juego y abre el menú correspondiente.

También hay que tener en cuenta lo de _tap, hold and release_. Porque si decimos que diferentes modos de apretar una tecla tienen diferentes efectos (por ejemplo, tap en una flecha hace que el heroe gire o de un paso, hold hace que camine), tenemos que enseñarlo en algun lado.

**Comment by einacio** [comment]
lo de tap/hold puede llegar a ser intuitivo en las teclas de direccion,
pero con las acciones es mas complicado

2015-10-05 16:38 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
tengo un archivo de excel con unas 50 acciones mas o menos que se pueden hacer con combinaciones de teclas. No sé si las vamos a implementar todas, pero la posiblidad existe.

**Comment by zenieldanaku** [comment]
Se me ocurría recién (14/12/2015) que usando TapHold se abren muchas más opciones de intereacción en contexto de los diálogos (#28). Concretamente, se me ocurría que tapping en la tecla de hablar hace cambiar la pagina o confirma una selección, pero hold podría abrir un menú, o un nuevo set de opciones, mostrando por ejemplo los objetos del inventario, o cosas así.

**Comment by zenieldanaku** [comment]
En el primer post digo que Shift tiene más bien poco efecto: lo único que hace es cambiar la posición del héroe en el modo aventura. No tiene funciones más allá de ese mob, en ese modo. A lo cual, se me ocurre, podríamos usar la opción que aparece en Sword of Mana para GBA: el personaje entra en "modo combate" (saca la espada) automáticamente en presencia de monstruos. Podríamos hacerlo mediante scripting también, o mediante un menú (el menú circular, por ejemplo).

**Comment by einacio** [comment]
el tema es que si hacemos eso, no hay posibilidad de pegarle a un mob
neutral si no hay monstruos cerca (lo que quita la posibilidad de cambios
de relaciones con las facciones), y tendriamos que hacer que los npc sean
invulnerables para no matar algun sin querer si llega a haber un monstruo
cerca.

2016-03-04 11:13 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
No digo que quitemos del todo la posibilidad de sacar el arma en cualquier momento. Digo que lo hagamos de otra forma (como por ejemplo, con el menu circular) en lugar de dedicarle una tecla entera a esa sola acción. Aparte de esa forma "voluntaria" de sacar la espada, también podríamos scriptearla para que el pc la saque automaticamente en determinados momentos, o que la saque automáticamente (como el sword of mana) en presencia de monstruos.

**Comment by einacio** [comment]
un menu que sea rapido de acceder me parece bien, y lo del desenvainado
automatico lo pondria como una opcion del juego (depende del mod, de ultima
ponemos un script de ejemplo y la forma de hookearlo).


2016-03-04 11:53 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
El tutorial del juego depende precisamente del juego, y no es territorio del engine en sí. Si un modder quiere entender cómo programar el engine, que lea la documentación. Hasta no haya un "juego" propiamente dicho no hay necesidad de un tutorial que lo explique.
