### ISSUE TITLE
Agregar un Trigger a las salidas

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#71]
Si las salidas son un objeto y no solo un rect (como lo son) entonces la class Salida debería tener un método "trigger" que le dijera al engine que cargue el mapa al cual la salida direcciona. Por ahora, esto lo hace directamente el héroe.
Además, este trigger podría lanzar un evento, de manera de, por ejemplo, setear flags.

**Comment by einacio** [comment]
Pisar una salida ahora lo esta detectando el PC? Capaz debería detectarlo
la salida como parte de su update, así también podría sacar del mapa a
otros mobs :)

**Comment by zenieldanaku** [comment]
Sí, lo está detectando el PC (el código es viejísimo), y solo para el PC, pisar una salida tiene una significación especial: que el PC pise la salida hace que el mapa que se le muestra al player cambie. Que un mob cualquiera pisara una salida (que por ahora no tiene efecto, porque no la detecta) no implica que el mapa cambie, más bien que el mob en cuestión desaparece del mapa.

**Comment by zenieldanaku** [comment]
Just for fun, busqué qué tan viejo es el código que hace que el héroe detecte las salidas: Data del 22 de Julio de 2014, en un update que se llamó "Rehabilitadas las Salidas".
