### ISSUE TITLE
AzoeEntity como algo real?

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#73]
Una pregunta: te parece que AzoeEntity sea a AzoeSprite lo que mapX le es a rect.x? Es decir, AzoeEntity sería, segun este criterio, un objeto "real" del mapa, mientras que todo lo que sea sprite (que además puede ser Entity) es algo "visible" pero no necesariamente real. Es una distinción parecida a lo que hago con las sombras (de hecho, estoy usando los mismos nombres "real"/"visible"). De esta forma, las salidas por ejemplo serían entidades (y tendrían métodos como reubicar()), pero no necesariamente Sprites, porque si bien existen en el _mapa_ el renderer no las ve ni les importan.

**Comment by einacio** [comment]
No se, no es complicar mucho las cosas tener 2 clases sólo por la imagen?

**Comment by zenieldanaku** [comment]
No es solo por la imagen. Ser un sprite implica por ejemplo, que la clase tiene un sprite__g, a lo cual la instancia se puede agregar a LayeredUpdates.

**Comment by zenieldanaku** [comment]
AzoeEntity también tendría mapX, mapY, stageX, stageY y posiblemente también z, pues esos son todos atributos reales.

**Comment by zenieldanaku** [comment]
Cierro este issue y fleto AzoeEntity entonces?
