### ISSUE TITLE
Estructuras complejas y compuestas

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#75]
En lugar de listar las casas y sus puertas por separado como objetos sueltos en el mapa, se me ocurre que podriamos crear un nuevo tipo de objeto "estructura", que estaria compuesto de varios otros objetos (en este caso, la casa está compuesta de 2 sprites: el suyo propio y el de la puerta). 
Si esta estructura está asociada a un json, entonces podemos definir datos para esa estructura (incluyendo un nombre) como por ejemplo si es relevante para una quest o si su puerta está cerrada con llave.

De la misma forma, podriamos listar las vallas de palotes con un solo archivo, en lugar de tener una lista enorme de posiciones en el mapa. Claro, esto es trasladar datos de un lugar a otro simplemente, pero me parece que así el trabajo es más "modular" y quizás algo más legible también.
En el caso concreto de la valla, se gana también algo de legibilidad, dado que las posiciones en x e y pasan a ser numeros relativos a la valla, no a todo el mapa (es decir, la primer valla estaría en 0,0, la segunda en 32,0, y así sucesivamente).

**Comment by einacio** [comment]
Me parece una buena oportunidad de modularización y simplificación

**Comment by zenieldanaku** [comment]
Otra cosa que se relaciona con esta es algo que habíamos hablado sobre usar un json para que un mismo objeto tuviera mas de una cara (habiamos hablado concretamente sobre los palotes). Se me ocurre usar una denominación parecida a la que se usa para determinar el tipo de una oración en inglés:
**estructura _compleja_**: objeto con más de una cara (frente, lado, reverso)
**estructura _compuesta_**: entidad formada con más de un objeto (casa, puerta, ventana).

Un objeto podría ser, como una oración, compuesto y combinado a la vez (un ejemplo serían las vallas de palotes, si las fueramos a considerar como un único objeto)

**Comment by zenieldanaku** [comment]
El único tema sería que un objeto así (complejo combinado) tendría las dos posiciones a la vez, y habría que determinar en algun lado qué cara se está usando, por ejemplo.

**Comment by einacio** [comment]
Apoyo. Escribís un borrador de especificación para ambos tipos?

**Comment by zenieldanaku** [comment]
voy a trabajar en eso
