### ISSUE TITLE
Creación dinámica de clases para mobs

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#76]
Hace ya bastante que separé a Mob en sus múltiples CompoMob, de manera de tematizar mejor el trabajo. Si bien la mayoría de los compomob son componenentes fijos de Mob, no sucede lo mismo con Parlante. Tanto NPCSocial (que ya no existe) como PC heredan de Parlante, pero Mob directamente no, porque no todos los mobs hablan.

Dicho eso, se me ocurrió borrar la clase NPCSocial, y dejar que NPC herede siempre de Parlante "todos los NPCs son parlantes". Pero, qué pasa con los mobs agresivos? Dije en el commit que iba a hacer una clase "mook" para ellos, pero luego se me ocurrió que la clase para ese tipo de mob (y para cualquier otro, realmente) podría hacerse dinámicamente.

Digamos que en el archivo de definición del mob estarían las palabras que corresponden a sus clases: ["Agresivo","invulnerable","fantasmagorico"]
Esas tres con Compomobs, o clases definidas por el usuario también, y luego Stage.Loader usa type() para crear la clase dinámicamente.

Te parece?

**Comment by einacio** [comment]
Me parece bien tener la posibilidad de crear nuevas clases dinamicamente,
pero no me parece mal tener un par de clases comunes precreadas como para
que sea menos verbose el archivo

2016-02-22 10:10 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
Y estoy viendo también como entrelazar esto con AzoeEntity... porque en
teoría, todos los mobs son entidades, y cargan datos desde un json, asi que
Entitiy juega.

**Comment by zenieldanaku** [comment]
Desde que se perdió la distinción entre PC y NPC, este issue perdió validez porque se basa en que ciertos mobs son distintos de otros. Habíamos dicho que esto es falso, porque las únicas diferencias entre mobs son de datos (qué imagen usan, qué actitud tienen, etc.) y eso es algo del mod, no del engine.
