### ISSUE TITLE
Usar el Event Loop Interno en lugar de Modos

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#77]
Ha sido mencionada ya en un par de issues (#65 y #67) la posibilidad de usar el _event loop interno_ que tenemos (register, trigger, process) para controlar las acciones del héroe. Si extrapolamos un poco, podemos controlar con eventos a los menues y a los diálogos también.

La razón de ser de Modos era la de capturar los eventos del teclado (de pygame) y convertirlos a la lógica del juego. Pero desde TapHold&Release (#55) esa conversión queda enmarcada en taphold.get_taphold_events(), a lo que el if/elif de Modos queda algo redundante.

Te parece sacarlo, en favor de los eventos?

**Comment by einacio** [comment]
hay que probarlo, para ver que no haya conflictos.
esta bueno porque desacopla bastante (modos ahora tiene una dependencia en
ciertas instancias en variables, y agregar cualquier otra cosa controlable
tendria que agregarse ahi). hay que ver que no agregue mucho delay (por
ejemplo, que no se que el teclado spamee la cola y empiece a retrasar los
frames

2016-03-04 10:43 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
Suena como trabajo de un branch, dicho así. 

Dudo que el teclado fuera a spamear la cola, porque a lo sumo el usuario pone uno o dos eventos por frame, a veces ni eso (digo, no es que el frame dure tanto como para poder teclear muchas veces). Mientras que no permitamos combinaciones de teclas (y creo que aún si las permitiésemos), el teclado no agregaría, me parece, mucho delay.
