### ISSUE TITLE
Preguntas sobre la documentación

### ISSUE THREAD

**Issue by einacio** [ludica-squamata/mano-gift#78]
b2c71ce20b844d3dd1d3a9c1019a2891a9a3055a 
Respecto de estructuras, cual es la ventaja de tener 3 tipos en vez de uno solo (el compuesto 3d)?
Compuesto es lo mismo pero con una sola cara cargada, y complejo(que se entendería más si fuera Tridimensional o algo parecido) sólo tiene cargado un elemento por cara. Con una sola clase cubrimos todaa las variantes y no tenemos 2 parsers que básicamente no se van a usar.

Sobre items, no hay Items que no sean escenografía? Por ejemplo que te lo de un npc, o se obtengan al abrir un cofre. (Con que clase se definiría un cofre?)

**Comment by zenieldanaku** [comment]
_Compuesto _es un objeto formado por varios otros objetos, los cuales pueden ser de distintos tipos. En el ejemplo que puse, la casa no tiene interacción (igual que los árboles), pero la puerta sí es un Operable, porque el hero la puede abir y cerrar.

_Complejo _(o tridimensional) es un objeto con varias caras (que, en un futuro, podria ser rotado para ver las otras caras). Cada cara del objeto es, en principio al menos, el mismo objeto, a lo cual tiene los mismos métodos (por ejemplo, si el palote fuera Destruible, todas las caras de ese objeto lo serían, no tendría sentido que una cara fuese destruible y las demás no).

Y sobre Ìtems, _Escenografía _denomina lo que aparece sin más en el mapa (al igual que los árboles o las casas). Un ítem que te da un NPC es eso mismo, un _Item_ (un objeto que existe en el inventario, no en el mapa). Un cofre sería una especie nueva de Escenografía (un _contenedor_, una especie de inventario en paquete) porque sería **visible en el mapa**.

Puede que sea confuso porque por ejemplo, la estrella es la vez Escenografía _Agarrable_, que pasa a ser un Ítem _Consumible _cuando el PC lo agarra del mapa. Si el héroe fuera a dejarlo de vuelta en el mapa (dropeandolo por ejemplo) volvería, en teoría, a ser tipo Escenografía, subtipo Agarrable.

Tanto Escenografía como Ítem son _props _(palabra que tomo del entorno de teatro, asi como escenografía). La denominación de Complejo y Compuesto la estoy tomando, como dije, del cómo se denominan las oraciones en inglés: una oración con dos sujetos y dos verbos es compuesta, una que tenga una clausula independiente y una dependiente es compleja. Una oración que tenga dos nucleos (sujeto y verbo) y una clausula independiente y una dependiente, es una oración compleja y compuesta.

**Comment by einacio** [comment]
Entendí que era cada una, pero teniendo _Objeto_Compuesto_Y_Complejo_ como
clase, que necesidad tenemos de las otras dos clases? Son sólo use cases
(infrecuentes además), y por lo tanto redundantes.

Lo Props agarrables, necesitan el subtipo? No basta con que sean
contenedores? Es irrelevante en que se  transformen después, hasta donde yo
veo

**Comment by zenieldanaku** [comment]
Se me ocurre que _frente_, _lado_ y _reverso_ podrían ser algo así como palabras clave, y las refs solo esperarían una imagen con esas palabras. Todo lo demás serían literales (nombres) cuyas refs apuntarian a definiciones de objeto, en cualquier otro caso debería tirar un error. Te parece así?

La distinción entre equipable y consumible en Agarrable tiene que ver con el Menu Equipo. Los items consumibles no se muestran (se filtran) en ese menú, y tanto en el Menú Circular como en el Menú Items, los ítems consumibles se diferencian de los equipables (en Menu Circular por categoría, en Menu Items por color).
