### ISSUE TITLE
Las sombras son estáticas

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#80]
Debido a la forma en la que se genera la sombra de un mob (tomando como base la imagen actual) por mucho que se mueva, cambie de estado o de dirección, la sombra permanece invariable, cuando debería cambiar junto al mob. 

Se me ocurre que, en lugar de usar sólo la imagen actual como base, podrian usarse todas las imagenes del mob en las distintas posiciones, aunque no estoy del todo seguro de que eso no sería muy lento.

También, la sombra debería cambiar con la iluminación (#57). Esto está previsto en el código, pero como aún no hay más luces que la del sol (DayLight), y ésta no se mueve, las sombras no cambian.

Finalmente, el largo de las sombras debería tener relación con el ángulo que forma el sol con la tierra (o sea, la hora del día y la latitud). Es una ecuación trigonométrica, y la función yo ya la tengo, pero no está aplicada al código todavía.

**Comment by einacio** [comment]
El diseño original consideraba el que la sombra se calcule con el lado
correcto, pero creo que nunca hice la función que obtenía la imagen del
objeto/mob desde otra cámara.
