### ISSUE TITLE
La velocidad del PC puede que sea demasiado alta

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#84]
Me puse a comparar la velocidad del heroe con la del commoner (seteado a caminar en una linea recta) y re descubrí lo que ya sabía: el pc es mucho más rapido que el npc. Pero me puse a pensar luego ¿por cuánto?. Dado que el pc se mueve junto a la cámara (más bien, la cámara es la que se mueve, no el pc), y que todo lo que no es el pc se mueve al revés que la cámara (o sea, si la cámara tiene un movimiento en +x, el mob lo tendrá en -x), para que el NPC se mueva a la misma velocidad que el PC, su velocidad tendría que ser de 9. 

No estoy seguro, pero quizás habría que setear eso de alguna otra forma.

**Comment by einacio** [comment]
que la camara se mueva al reves que el mob es irrelevante para comparar la
velocidad, ambos se mueven sobre mapX/Y a la velocidad que les corresponda,
y la camara solo apunta a otro lado.
si ambos tienen la misma velocidad, caminando uno al lado del otro deberia
parecer que la camara sigue a ambos

2016-03-31 14:38 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
Exactamente. Con la velocidad base del NPC seteada  a 1px y la del heroe seteada a 3px, el heroe siempre rebasa al NPC (como es esperable). Pero, incluso sin cambiar la velocidad del héroe, la velocidad del NPC tiene que ser de 9px para que pueda correr codo a codo con el heroe, y, dado que 9 pixeles es mucho movimiento, el npc salta de punto en punto.

**Comment by einacio** [comment]
si PC se mueve de a 3px y NPC de a 9, como es eso codo a codo? a menos que
los intervalos de actualizacion esten mal seteados (por ejemplo, que el
teclado se pollee mas veces por frame que update, o que el NPC se mueva
solo cada 3 frames) o que el PC tenga un multiplicador de velocidad en
algun lado (un modo correr). ambos en 3 deberian moverse a la misma
velocidad con camara o sin camara. si la camara influye, es un error (puede
comprobarse en una esquina del mapa, donde la camara no se mueve)

2016-03-31 15:47 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
Con el nuevo Behaviour Tree el NPC se mueve cada 3 ticks, sí.

**Comment by einacio** [comment]
le toma 3 frames decidir hacer un paso y otros 3 adelantar el otro pie? eso
no lo va a solventar triplicarle la velocidad entonces, solo va a quedar
clunky y si cambia tu algoritmo de decision tenes que reajustar todos tus
mobs. y los combates van a ser demasiado faciles me parece, porque si
apreto rapido atacar reviento a cualquier monstruo que tarda 3 o 5 frames
en decidir si me pega o no cada vez que lo hace.

3 frames deberia tardar en elegir el destino final y armar el path, y
entonces en cada frame se repite "mover hasta llegar a destino". (esa
accion deberia controlar dentro del mismo frame si hay un obstaculo en el
siguiente paso del camino planeado, y si esta bloqueado volver al
planeamiento de 3 frames)
es de la misma manera que funciona un jugador: mira la pantalla, elije a
donde ir y mantiene la flecha hasta llegar.



2016-04-01 8:29 GMT-03:00 Daniel <notifications@github.com>:

> Con el nuevo Behaviour Tree el NPC se mueve cada 3 ticks, sí.
>

**Comment by zenieldanaku** [comment]
El issue #135 trata con el problema que quedó de este issue (el tema de la grilla y la detección de colisiones mediante A*).
