### ISSUE TITLE
Deshacer la clase Constants en un módulo con constantes

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#85]
Lo dicho. Desde hace un tiempo que vengo pensando que las constantes deberían estar sueltas en el módulo, como creo que se hace en cualquier otro lado (onda `from constants import *`, como se hace en tinkter y en pygame). No le veo mucho el objeto a tenerlas agrupadas en una clase, con excepción quizás de _Teclas_ que, al poder cambiar, no debería ser una **constante**.

**Comment by einacio** [comment]
las nuestras no son contantes tan usadas, no hace mucha diferencia. es mas
una cuestion de gustos, pero es practico mantenerlas con su namespace
cuando hay riesgo de colision con otro modulo (que en nuestro caso no creo
que pase)

2016-04-09 19:37 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
Que hago con este issue entonces?

**Comment by einacio** [comment]
como es una cuestion de gustos, yo diria que vayas con la forma que mas te
guste
