### ISSUE TITLE
Simplificar las teclas

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#86]
Creo que esto lo habías mencionado vos en algún momento, pero se me volvió a ocurrir a mi ayer, que podríamos setear la tecla "Accion" como algo contextual: si estoy frente a un item, funciona como agarrar, o empujar, o abrir. Si estoy frente a un mob, y no tengo la espada en la mano, es hablar, si no, atacar. De esta forma se eliminaría Hablar, y simplificaríamos un poco el tema de los botones.

**Comment by einacio** [comment]
si, segun lo veo, si no estoy en combate, la accion predeterminada con otro
mob es hablar, asi que no tendria sentido separarlas

2016-04-17 11:20 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
El tema seria qué pasa si queres *hablar en combate*. Aunque la mayor parte
de los juegos no tienen ese feature, y si lo tienen son taunts o
conversaciones scripteadas, porque el player está ocupado peleando.

**Comment by einacio** [comment]
Para habla en combate cambias de modo. Sólo tiene sentido tener dos botones
si todos los juegos del engine usarán esa mecánica, que no creo. Si algún
juego particular quiere hacerlo, puede agregarlo por mod o modificando su
copia del engine(que al fin y al cabo por algo es open source)

**Comment by zenieldanaku** [comment]
Estaba trabajando en este issue cuando me di cuenta de que lo mismo ocurre con menu rápido (antes _inventario rápido_) y Cancelar diálogo, y pensé que también deberiamos fusionarlas.

Esto nos dejaría en 3 comandos -  Interactuar (atacar, hablar, confirmar), Contextual (menu rápido, cancelar diálogo, menú previo), Pausa (el menú) - y las teclas de movimiento. Te parece así?

**Comment by einacio** [comment]
me parece bien. a la altura que estamos en el desarrollo no necesitamos
realmente mas botones que un NES. si tuvieramos algo como habilidades
activadas podriamos llegar a necesitar mas, pero la verdad es que
normalmente los juegos tienden a gravitar hacia controles mas simples
igualmente.
en ultima instancia, podemos dejar internamente que sean diferentes teclas
mapeadas a esas 2 por defecto, y si despues alguien quiere complicarse la
vida mapeando todo el teclado que lo haga

2016-05-15 17:38 GMT-03:00 Daniel <notifications@github.com>:
