### ISSUE TITLE
Player Character vs Mob  Hero

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#89]
Con la nueva adición del menu personaje, que permite ingresar el nombre, llega próximamente la opción de guardar la partida. Concretamente, el primer dato que se estaría guardando es el nombre. Pero con esta nueva opción viene una pregunta: dónde debería guardarse ese dato?

La descripción básica del mob "heroe" es identica a la de otros mobs, y luchamos mucho para que el héroe no fuera más especial que otros mobs. A lo cual, me parece, el archivo de guardado donde figura su nombre y estados deberia ser otro, en otro lado (una carpeta que no tenemos: no va ni en engine, ni en mod, ni en docs!)

**Comment by einacio** [comment]
si queres mantener los archivos claramente separados (por ejemplo para que
sea facil migrar un savegame a otra pc), simplemente podes crear una
carpeta mas, por ejemplo saveData, y crear los archivos ahi. ese nombre
deberia estar agregado en el gitignore, y crearse automaticamente si no
existe.
ahi guardamos todo lo que sea configuracion de usuario: teclas, nombre de
su personaje, memorias de los npc, etc

2016-06-25 15:24 GMT-03:00 Daniel <notifications@github.com>:
