### ISSUE TITLE
Mejorar la performance en la generación de sombras

### ISSUE THREAD

**Issue by danielrossyamitrano** [ludica-squamata/mano-gift#91]
Estaba probando la generacion de sombras por el evento de hora, y logré que aparecieran las sombras que tenemos (NE y NO), pero sucede que hay un notable delay cuando se generan las nuevas sombras. Al respecto, se me ocurrió que muchas sombras son idénticas (todos los arboles, por ejemplo, tienen las mismas sombras, al igual que las casas o los palotes). Por lo tanto, creo, ganaríamos mejor performance si solo generarmos la sombra para 1 arbol, 1 casa y 1 palote, y luego lo replicaramos por todos los sprites que son idénticos. En lugar de repetir el mismo procedimiento una y otra vez sobre surfaces que son idénticas.

**Comment by zenieldanaku** [comment]
Generar las sombras de este modo requería agrupar los sprites idénticos dentro de algun tipo de conjunto, por lo que las sombras ya no se generarían mediante el update del sprite.

**Comment by einacio** [comment]
las sombras se pueden agrupar por sprite, usando la ruta de la imagen como
clave en un dict o algo similar
