### ISSUE TITLE
Glitches al caminar y atacar a la vez

### ISSUE THREAD

**Issue by zenieldanaku** [ludica-squamata/mano-gift#95]
Si el PC camina en estado "cmb"  y ataca, ocurren dos glitches:
1. La animación del ataque se vé entrecortada por de caminar
2. Si se ataca y camina cerca de un prop sólido, cabe la posiblidad de que el PC quede trabado en el prop, dado que al cambiar su máscara de ataque, ésta colisiona con la mascara del prop. Este glitch también permite atravezar barreras como los palotes.

Soluciones que se me ocurren son:
1. No permitir que el PC camine y ataque al mismo tiempo
2. Mantener de algun modo las animaciones y las mascaras separadas (self.image y self.mask son el problema)

**Comment by zenieldanaku** [comment]
Se me acaba de ocurrir que una solución a este issue que no limite los movimientos del personaje podria ser que las piernas y el torso del personaje se movieran independientemente. Mover() animaría las piernas, mientras que el resto del cuerpo se animaría según si el personaje esta en modo cmb o idle.

**Comment by zenieldanaku** [comment]
Para lo anterior habria que hacer que en alguna parte (posiblemente en la definición del mob) se indicara dónde termina el torzo y empiezan las piernas (podria indicarse con un rect). Esto implicaría que el mob se "renderiza en runtime", como si fuera un engine 3D con texturas.

**Comment by einacio** [comment]
El renderizado compuesto es una buena opcion, posiblemente podria
prerenderizarse en memoria a medida que se necesite.

Igual esto no soluciona el tema de la mascara que atravieza. Para eso lo
que habria que hacer es que en el momento en que se cambia la mascara hacer
un checkeo de colisionesen las 4 direcciones y empujar hacia atras el mob
si alguna estuviera encima de algo

2017-03-23 17:50 GMT-03:00 Daniel <notifications@github.com>:

**Comment by zenieldanaku** [comment]
O no cambiar la máscara y usar la máscara de ataque y la de movimiento como máscaras independientes. En este momento estamos haciendo `self.mask = self.atackmask` básicamente, cuando bien podriamos chequear la colisión contra la máscara de ataque directamente, me parece.

**Comment by zenieldanaku** [comment]
Perdón, corrijo mi comentario anterior: la mascara que atraviesa directamente no existe ya, se usa el selector por cuadrantes para detectar esa interacción.

**Comment by zenieldanaku** [comment]
Si bien la solución implementada no me gusta, hace rato ya que este issue debería haber sido cerrado, porque el glitch que se menciona al inicio ya está solucionado con una de las respuestas dadas en el mismo comentario.
